/// Flutter icons Weathernw
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Weathernw
///      fonts:
///       - asset: fonts/Weathernw.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Weathernw {
  Weathernw._();

  static const _kFontFam = 'Weathernw';
  static const String? _kFontPkg = null;

  static const IconData water = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wind = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
